### ISSUE TITLE
a question regarding offset management

### ISSUE THREAD

**Issue by skyahead** [mmolimar/kafka-connect-fs#1]
Hi Mario,

I wonder while ingesting a file and somehow the code crashed, when it resumes, how kafka-connect-fs knows which line to restart with? Will it write duplicated lines into Kafka?

**Comment by mmolimar** [comment]
Hi!
When delivering the record from the connector, it includes the corresponding offset of that record (received from the file reader). Eventually, the offset will be committed and the policy will know what offset is the last one it has to process, so there won't be duplicated records (in this case).

However, if **the offset has not been committed** when re-processing the file (depending on your configuration), the file reader won't know where to seek the file to process new records and then, you will find duplicates.

**Comment by skyahead** [comment]
Does it make sense to use a local file to keep the offsets that are
committed, so that when resuming, offsets can be read from these local
files?

**Comment by mmolimar** [comment]
Not exactly. The framework manages the offsets for you, you don't have to worry about that.

**Comment by skyahead** [comment]
Thanks Mario!
