### ISSUE TITLE
[Feature Request] Add SFTP support

### ISSUE THREAD

**Issue by o3661606** [mmolimar/kafka-connect-fs#11]
Currently the connector is using Hadoop 2.7.3
Meanwhile Hadoop 2.8 is released and SFTP filesystem is added ([Details here](https://issues.apache.org/jira/browse/HADOOP-5732))
Will you add the support of SFTP in the future?

**Comment by mmolimar** [comment]
Yeah! I hope to do it very soon :-)

**Comment by mmolimar** [comment]
I've upgraded the Hadoop version (2.9.0) and it has already support for SFTP.
