### ISSUE TITLE
DelimitedTextFileReader sets all fields as Required

### ISSUE THREAD

**Issue by agouz** [mmolimar/kafka-connect-fs#13]
Hello team,
The DelimitedTextFileReader.java creates a schema based on the header in the csv file, all fields are created as Required by default. This breaks the conversion in case one column is empty and throws "Conversion error: null value for field that is required and has no default value".
It would be great if this can be configurable.

**Comment by mmolimar** [comment]
Hello!
This functionality has been included in this file reader. It's currently in the master branch.
