### ISSUE TITLE
Duplicates messages in Topics for HDFS

### ISSUE THREAD

**Issue by breadfan** [mmolimar/kafka-connect-fs#16]
I have a test setup (landoop, coyote, hadoop docker) for 2 messages written to HDFS, and try to read it again with this setup:

```
{
  "name": "hdfs-source",
  "config": {
    "connector.class": "com.github.mmolimar.kafka.connect.fs.FsSourceConnector",
    "tasks.max": "1",
    "fs.uris": "hdfs://hadoop:9000/topics/net.gutefrage.events/",
    "topic": "net.gutefrage.replayed-events",
    "policy.class": "com.github.mmolimar.kafka.connect.fs.policy.SleepyPolicy",
    "policy.sleepy.sleep": "10000",
    "policy.recursive": "true",
    "policy.regexp": ".*\\.avro",
    "file_reader.class": "com.github.mmolimar.kafka.connect.fs.file.reader.AvroFileReader"
  }
}
```

Update: The problem does not occur with the Simple Policy.

It works, but instead of the expected 2 messages I see 22: 20 duplicates of the 2 messages. is this a bug or a misconfiguration?

**Comment by mmolimar** [comment]
Have you read [this](http://kafka-connect-fs.readthedocs.io/en/latest/faq.html)?

**Comment by breadfan** [comment]
Thanks for the answer. No I haven't. I do understand now why this happens.

Several months ago I wrote a connector by myselfs (fetching files from Google cloud storage and adding the contents to Kafka. I now realize that I've run into some issues which are resulting from the deferred commit of the offsets as well. 

What I did in my connector is that I used an synchronized in-memory-storage for the offsets inside the task, and only if that is empty I take the offsets provided by Kafka connect. So when the task / connector is stopped/crashed and restarted, the operations are resumed from the last committed offset, but when everything works normal, the In-memory Offsets are used.  With that approach I think I do not loose anything and reduce the duplicates to a minimum if everything operates well. Also I don't have to configure the task schedule or parameters of the connector so that it works together with the worker configs (i.e. commit offset schedules).

IMHO I really don't like that I should configure the connector so that it works nicely with the commit offsets schedule/flushing whatever....

**Comment by breadfan** [comment]
No comments on my thoughts?

**Comment by mmolimar** [comment]
I don't think that would be a good idea. Not at least if you have a local cache in order to do that.
If you just have one node (which is not very usual in a production deployment) could be work if you manage properly the synchronization between the committed offsets and the cache but... if not? Using a distributed cache? I think it's too much for this case...
