### ISSUE TITLE
NullPointerException when using FTP uri

### ISSUE THREAD

**Issue by vanmeete** [mmolimar/kafka-connect-fs#18]
Trying to use the kafka-connect-fs connector to access csv files on a FTP server, however receiving the following

org.apache.kafka.connect.errors.ConnectException: An error has occurred when creating reader for file: ftp://user:password@ftpserver:21/csv/1.csv
        at com.github.mmolimar.kafka.connect.fs.policy.AbstractPolicy.offer(AbstractPolicy.java:212)
        at com.github.mmolimar.kafka.connect.fs.policy.SleepyPolicy.offer(SleepyPolicy.java:11)
        at com.github.mmolimar.kafka.connect.fs.FsSourceTask.lambda$poll$0(FsSourceTask.java:82)
        at java.util.ArrayList.forEach(ArrayList.java:1249)
        at com.github.mmolimar.kafka.connect.fs.FsSourceTask.poll(FsSourceTask.java:79)
        at org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:163)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:146)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:190)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException

It looks like that the "setWorkingDirectory" method in the FTPFileSystem.class does not set the WorkingDirectory and defaults to root "/" .  This results in the filter in AbstractPolicy.offer not returning a current FileSystem.

**Comment by mmolimar** [comment]
Have you read the [documentation](http://hadoop.apache.org/docs/current/api/org/apache/hadoop/fs/ftp/FTPFileSystem.html) about this file system?
I don't know how your connector config is too...

**Comment by vanmeete** [comment]
I have gone throught the documentation, maybe i missed something. I'm using the following configuration:

_name=FsSourceConnector
connector.class=com.github.mmolimar.kafka.connect.fs.FsSourceConnector
tasks.max=1
#fs.uris=file:///data,hdfs://localhost:9000/
fs.uris=ftp://user:password@ftpserver:21/csv/
topic=csv_topic
policy.class=com.github.mmolimar.kafka.connect.fs.policy.SleepyPolicy
policy.sleepy.sleep=5000
policy.recursive=true
policy.regexp=.*
policy.fs.fs.ftp.data.connection.mode=PASSIVE_LOCAL_DATA_CONNECTION_MODE
policy.fs.fs.ftp.transfer.mode=STREAM_TRANSFER_MODE
file_reader.class=com.github.mmolimar.kafka.connect.fs.file.reader.DelimitedTextFileReader
file_reader.delimited.token=;
file_reader.delimited.encoding=UTF8_

the "data connection mode" and "transfer mode" are added and picked up by the connector. Debugging the connector gives me.

AbstractPolicy.java
  line 70: fs.setWorkingDirectory(workingDir); _wokringDir: "ftp://user:password@ftpserver:21/csv"_

  line 200: .filter(fs -> metadata.getPath().startsWith(fs.getWorkingDirectory().toString())) _metadata.getPath() returns fullpath: "ftp://user:password@ftpserver:21/csv/1.csv" and   fs.getWorkingDirectory() returns: "/"_ 

I would expect that fs.getWorkingDirectory returns _ftp://user:password@ftpserver:21/csv_ 

I'm missing something any help would be higly appriciated

**Comment by mmolimar** [comment]
I think you should set some other properties in the config file (users, pass, etc). You can check it out [here](http://hadoop.apache.org/docs/current/api/constant-values.html#org.apache.hadoop.fs.ftp.FTPFileSystem.FS_FTP_DATA_CONNECTION_MODE).

On the other hand, which version of the connector are you using? If it's not the latest, could you upgrade to the latest version?

**Comment by vanmeete** [comment]
I have been using version 1.2 and master from a few days ago to have hadoop version 2.9.0, I also tried today the latest 2.0 release, the result is the same. 

All the needed properties for the FTPClient are set; user, password etc are fetched from the uri. 

The connector uses the setWorkingDirectory and getWorkingDirectory methods and as I see it (when using ftp uri) the setWorkingDirecotry method in the FTPFileSystem.class is not "implemented".  
Meaning line 70 in the AbstractPolicy.class doesnot do anything when using FTPFileSystem (ftp uri). 

The getWorkingDirectoy method from the FTPFileSystem returns root "/", therefor the filter in AbstractPolicy (line 200) is false and is causing the "current" filesystem to be null.  

Changing line 200 in AbstractPolicy to 
 _.filter(fs -> metadata.getPath().startsWith(fs.getScheme()))_ solves it for me, 

One thing left is that the folder (when using ftp:/...) specified in the fs.uri is not honored, but i can live with that.

Thanks, appreciate your time and effort.

**Comment by mmolimar** [comment]
Yes, you're right. FTPFileSystem class does not maintain the working directory state so, that's the reason. If that workaround works for you, great :-)
