### ISSUE TITLE
Error while try to uploading text file to kafka

### ISSUE THREAD

**Issue by anuhewa** [mmolimar/kafka-connect-fs#23]
Error as below

==========================================================

[2018-02-01 13:51:20,178] ERROR Failed to create job for client.properties (org.apache.kafka.connect.cli.ConnectStandalone:97)
[2018-02-01 13:51:20,179] **ERROR Stopping after connector error** (org.apache.kafka.connect.cli.ConnectStandalone:108)
java.util.concurrent.ExecutionException: org.apache.kafka.connect.runtime.rest.errors.BadRequestException: Connector config {security.protocol=SASL_PLAINTEXT, sasl.kerberos.service.name=kafka} **contains no connector type
        at org.apache.kafka.connect.util.ConvertingFutureCallback.result(ConvertingFutureCallback.java:79)
        at org.apache.kafka.connect.util.ConvertingFutureCallback.get(ConvertingFutureCallback.java:66)
        at org.apache.kafka.connect.cli.ConnectStandalone.main(ConnectStandalone.java:105)
Caused by: org.apache.kafka.connect.runtime.rest.errors.BadRequestException: Connector config** {security.protocol=SASL_PLAINTEXT, sasl.kerberos.service.name=kafka} contains no connector type
        at org.apache.kafka.connect.runtime.AbstractHerder.validateConnectorConfig(AbstractHerder.java:242)
        at org.apache.kafka.connect.runtime.standalone.StandaloneHerder.putConnectorConfig(StandaloneHerder.java:163)
        at org.apache.kafka.connect.cli.ConnectStandalone.main(ConnectStandalone.java:102)

==================================================================

text file as below

=============================================

[root@hostname connectsource]#
[root@cdhant1 connectsource]# **cat test.txt**
asd,qwe,asd,qwe,qwe
qaz,edc,rfv,tgb,yhn
[root@hostnameconnectsource]# pwd
**/datan1/connectsource**
[root@hostname connectsource]#

=============================================================

command = **KAFKA_HEAP_OPTS="-Xms512m -Xmx1g" $CONFLUENT_HOME/bin/connect-standalone $CONFLUENT_HOME/etc/schema-registry/connect-avro-standalone_properties
       config/kafka-connect-fs.properties       client.properties**

-----------------connect-avro-standalone_properties-----------------------------------------
bootstrap.servers=hostname:9092,hostname:9092

**key.converter=io.confluent.connect.avro.AvroConverter
key.converter.schema.registry.url=http://hostname:8083
value.converter=io.confluent.connect.avro.AvroConverter
value.converter.schema.registry.url=http://hostname:8083**

internal.key.converter=org.apache.kafka.connect.json.JsonConverter
internal.value.converter=org.apache.kafka.connect.json.JsonConverter
internal.key.converter.schemas.enable=false
internal.value.converter.schemas.enable=false

offset.storage.file.filename=/tmp/connect.offsets

-------------------------------------------------------------------------------------------

======================================

----------------------------kafka-connect-fs.properties---------------------------
**name=FsSourceConnector
connector.class=com.github.mmolimar.kafka.connect.fs.FsSourceConnector
tasks.max=1
fs.uris=file:///datan1/connectsource/
topic=test8
policy.class=com.github.mmolimar.kafka.connect.fs.policy.SimplePolicy

policy.recursive=true
policy.regexp=.*
file_reader.class=com.github.mmolimar.kafka.connect.fs.file.reader.TextFileReader**

==================================================================

-------------------client properties---------------------

security.protocol=SASL_PLAINTEXT
sasl.kerberos.service.name=kafka
----------------------------------------------------------------

**Comment by anuhewa** [comment]
Kafka connect supports for secured cluster ?
How to pass below two producer config with kafka connect standalone ?


security.protocol=SASL_PLAINTEXT
sasl.kerberos.service.name=kafka

**Comment by mmolimar** [comment]
I'm afraid this error has nothing to do with this connector.
Please, refer to the proper documentation. You can find more information in the [Confluent docs website.](https://docs.confluent.io/current/security.html)

**Comment by anuhewa** [comment]
Thanks i have overcome this with correct Kerberos config. (my configs available in below link)

Can you guide me on below issue ?(I need filename to be present , when i am consuming )

refer link

https://github.com/mmolimar/kafka-connect-fs/issues/24
