### ISSUE TITLE
Need to pass filename  and data to kafka

### ISSUE THREAD

**Issue by anuhewa** [mmolimar/kafka-connect-fs#24]
Currently i am able to listen file and upload to kafka and consume it as below.

Consumer sample output as below

Struct{value=mobile|imsi|2050160|2|14|2|xxxxxx|20160917|vvvvvv|20370101|mmmmmm|1250158,1104006,1210003,xxxxxx,1106000,54545454,1103001|2000:14,3000:-3333333|}
Struct{value=mobile|imsi|2050160|2|14|2|xxxxxx|20160917|vvvvvv|20370101|bbbbbbbbb|1250158,1104006,1210003,xxxxxx,1106000,44444444,1103001|2000:14,3000:-4444444|}

I need my file name to be present as key of above output.

My current configs as below

=================/kafka-connect-fs.properties==========================
name=FsSourceConnector
connector.class=com.github.mmolimar.kafka.connect.fs.FsSourceConnector
tasks.max=10

fs.uris=file:///dat/source
topic=topicname

policy.class=com.github.mmolimar.kafka.connect.fs.policy.SleepyPolicy
policy.sleepy.sleep=50000

policy.regexp=.*
file_reader.class=com.github.mmolimar.kafka.connect.fs.file.reader.TextFileReader

===================================properties======================

=======connect-avro-standalone.properties==========================

bootstrap.servers=ip:9092,ip:9092
key.converter=org.apache.kafka.connect.storage.StringConverter
key.converter.schema.registry.url=http://ip:8083
value.converter=org.apache.kafka.connect.storage.StringConverter
value.converter.schema.registry.url=http://ip:8083
internal.key.converter=org.apache.kafka.connect.json.JsonConverter
internal.value.converter=org.apache.kafka.connect.json.JsonConverter
internal.key.converter.schemas.enable=true
internal.value.converter.schemas.enable=true
key.converter.schemas.enable=true
value.converter.schemas.enable=true
sasl.kerberos.service.name=kafka
security.protocol=SASL_PLAINTEXT
producer.security.protocol=SASL_PLAINTEXT
producer.sasl.kerberos.service.name=kafka
sasl.kerberos.service.name=kafka
offset.storage.file.filename=/tmp/connect.offsets
plugin.path=share/java

====================================

I am executing as below

KAFKA_HEAP_OPTS="-Xms4g -Xmx32g" /confluent-4.0.0/bin/connect-standalone/ connect-avro-standalone.properties kafka-connect-fs.properties

Kindly advise

**Comment by mmolimar** [comment]
The filename is not sent to Kafka...
It's possible to extend the connector and add that functionality

**Comment by anuhewa** [comment]
Thanks a lot

Can i move "file which uploaded to kafka" , to another location ?

**Comment by mmolimar** [comment]
What do you mean?

**Comment by anuhewa** [comment]
i mean files which available in local file system .  after upload them to kafka  , can i move them to another location with out any external programme ? (I mean from connectot config it self ?)

**Comment by mmolimar** [comment]
I don't think so...

**Comment by anuhewa** [comment]
Below connector support it ?

https://github.com/jcustenborder/kafka-connect-spooldir

**Comment by mmolimar** [comment]
I do not know that connector
