### ISSUE TITLE
Change possibility for Schema Name and Namespace.

### ISSUE THREAD

**Issue by eherrerand** [mmolimar/kafka-connect-fs#25]
Hi, I've been testing the connector for a couple of days, focused on the DelimitedTextReader and CSV.
In our Test Case we're working with Avro (Specific Record) and Kafka Schema Registry.
The behaviour is really nice; using the CSV header to define column names, and COLUMN_# in case header is not define, but for the schema name/namespace there is not any configuration possibility.
Why we need to define a namespace? We have tons of CSVs and we expect to keep schemas orderered through namespaces, and schema names.

Thanks in advance,
BR.

**Comment by mmolimar** [comment]
What do you mean by defining a namespace? In the Avro schema?
