### ISSUE TITLE
How can I get the connector to "pace itself"?

### ISSUE THREAD

**Issue by woodlee** [mmolimar/kafka-connect-fs#28]
I'm trying to use this connector to do a historical replay from Kafka topic messages that were previously archived into S3 back into a new topic. Connector properties are as follows:

```
name=restore-from-s3-sa
tasks.max=1
connector.class=com.github.mmolimar.kafka.connect.fs.FsSourceConnector
topic=<my_topic>
fs.uris=s3a://<...snip...>/event_date=2018-02-28/
policy.sleepy.max_execs=1
policy.class=com.github.mmolimar.kafka.connect.fs.policy.SleepyPolicy
policy.sleepy.sleep=30000
policy.recursive=true
policy.regexp=.*\.avro$
file_reader.class=com.github.mmolimar.kafka.connect.fs.file.reader.AvroFileReader
transforms=createKey
transforms.createKey.type=org.apache.kafka.connect.transforms.ValueToKey
transforms.createKey.fields=<my_field>
```

The `event_date=2018-02-28/` folder contains several hundred Avro files of ~5 MB each. The issue I'm having is that even under this setup, with `tasks.max` set to `1` and running Kafka Connect in standalone mode, the connector seems to try to pull all of the files at once up-front before beginning to process them, so it's not long before I hit OOM errors. The logs will show several repetitions of the below (once per file) before other message about offset committing etc. begin to show up:

```
[2018-03-05 22:08:41,124] INFO io.bytes.per.checksum is deprecated. Instead, use dfs.bytes-per-checksum (org.apache.hadoop.conf.Configuration.deprecation)
[2018-03-05 22:08:41,564] INFO Processing records for file [path = s3a://<...snip...>/event_date=2018-02-28/mytopic_v1+1+0016543294.avro, length = 4657181, blocks = [[offset = 0, length = 4657181, corrupt = false]]] (com.github.mmolimar.kafka.connect.fs.FsSourceTask)
[2018-03-05 22:08:41,957] INFO AvroDataConfig values:
	schemas.cache.config = 100
	enhanced.avro.schema.support = false
	connect.meta.data = true
 (io.confluent.connect.avro.AvroDataConfig)
```

I've tried this in both standalone and connect modes, and have also tried just writing the individual file URLs into the `fs.uris` property and setting `policy.recursive` to `false`, with no luck. If I pare back the list of files to a small enough number, everything does seem to work as intended.

Also worth noting, though it _probably_ doesn't matter: I'm running Confluent Platform 4.0.0 / Kafka 1.0.0, so I built this connector with a few modifications to the dependency versions, namely:

`avro.version` 1.8.1 -> 1.8.2
`kafka.version` 0.10.1.0 -> 1.0.0
`confluent.version` 3.1.1 -> 4.0.0

Is there something I can change to drop the concurrency, or to ask the connector to process files serially within a task? Thanks!

**Comment by mmolimar** [comment]
The ``tasks.max`` property is used when you have several URIs and you want to process them in parallel.
When starting the policy, it list all files you have in that URI and then it goes processing one by one so I wouldn't say that the connector runs out of memory... I think having several hundreds of files in that directory is not too much...
