### ISSUE TITLE
Out of Memory Error at too many files

### ISSUE THREAD

**Issue by tanermelikoglu** [mmolimar/kafka-connect-fs#31]
Hi all,

i get following the connector try to read the files from a public ftp that has too many files (c.a. 470), which are updated every 10 minutes.

```
java.lang.OutOfMemoryError: Java heap space
[2018-04-27 20:06:37,662] ERROR Uncaught exception in thread 'kafka-producer-network-thread | producer-3': (org.apache.kafka.common.utils.KafkaThread)
```

Is there any configuration point to control how many files to read at one poll ?

**Comment by mmolimar** [comment]
Hi,

I'm afraid that there isn't a config option to set the max files to process. Instead, you can increase the sleep time.
Anyway, you could try increasing the heap memory in the JVM.

**Comment by WheresAlice** [comment]
I'm seeing the same issue, reading files from S3.  It used 11GB memory reading just 6 files, totalling 150MB.  We have 177 of these files, and a 64GB instance runs out of memory before committing anything to Kafka.  Setting the sleep time does absolutely nothing.

It looks like the connector is attempting to read all of the available files before it starts committing to Kafka.

This is only a problem for our initial load, and we are considering drip-feeding the S3 bucket - writing a script to upload one file to S3 per minute - and hoping that this connector does not need to keep the already-read files in memory too.

**Comment by kylecbrodie** [comment]
@WheresAlice @mmolimar I believe this has been resolved in version `1.1.0` with the policy config param `batchSize`

**Comment by mmolimar** [comment]
Yes, you're right @kylecbrodie.
Can we close this @WheresAlice ?

**Comment by tanermelikoglu** [comment]
Hey gus, i did not check if is working now in version 1.1.0. If you say it is ok, i close the issue.
