### ISSUE TITLE
Moving processed files

### ISSUE THREAD

**Issue by lachtomas** [mmolimar/kafka-connect-fs#33]
Hi Mario, I'm using FS connector with parquet file reader on linux filesystem, so every execution of policy seeks all the input parquet files. Is there anything to avoid this? I'm considering implementation of moving processed files to different directories (processed successfully -> output directory, error files -> error directory), to avoid that parquet seeking. 

What is your opinion? 
Thanks

**Comment by mmolimar** [comment]
Hi @lachtomas!
You may manage this using some kind of regex in your fs URIs. Anyway, if you processed a file and the offsets were committed, these record won't be sent to Kafka again.

**Comment by lachtomas** [comment]
Yes, it won't be sent to Kafka again, but i'm concerned with heavy parquet seeking at every policy execution. My parquet files are large, and there are many of them - processed files could be moved, and not seeked again.

**Comment by lachtomas** [comment]
Yes, but it would be great, if this connector will support feature of moving processed files (maybe not only parquet). What do you think about it? I would like to contribute.

**Comment by mmolimar** [comment]
Maybe it would be a good idea (if you can enable/disable this functionality and it'd be generic)
