### ISSUE TITLE
Kafka with Kerberos

### ISSUE THREAD

**Issue by mikhmakarov** [mmolimar/kafka-connect-fs#35]
Is it possible to use kafka-connect-fs to read files from kerberized hdfs and write to kerberized Kafka?

**Comment by mmolimar** [comment]
Yes, you have to configure properly the core-site.xml and the corresponding keytab to connect to an HDFS kerberized.

**Comment by mikhmakarov** [comment]
Well, and is it possible to simultaneously use kerberized hdfs and kerberized kafka?

**Comment by mmolimar** [comment]
Yes, but using the same principal.

**Comment by rbird85** [comment]
Out HDFS is kerberized but my Kafka is not. Could you please share instructions on how to connect to a kerberized HDFS using this connector? 
I have added core-site.xml to the classpath and have added the krb5.conf path to 'KRB5_CONFIG' env variable but it still doesn't seem to work.
