### ISSUE TITLE
New Files not getting picked up when the connectors are running.

### ISSUE THREAD

**Issue by srikant-mvs** [mmolimar/kafka-connect-fs#36]
I tested running this connector in my local machine in distributed mode. I configured 2 different rest endpoint 8083 and 8084. The "fs.uris" given is a local file directory from where it should pick. 
There are sub directories from where the data should be read and posted to kafka topic. 
When I created new sub-directory, the connector read that folder, 
but rather it was read by connector instanceB when i stopped connector instanceA.
The continuous polling is not happening.
Please advice if iam missing something

**Comment by srikant-mvs** [comment]
I used SimplePolicy and see that either when new files are added to an existing directory or when new lines are added to the existing files, the changes are not getting picked up unless the connector is restarted.

When I changed the policy to SleepyPolicy with a delay of 30sec poll, the files are getting added to the topic twice with a difference in timestamp of 30 seconds.

Any inputs would be appreciated.

-Thanks 
Srikant

**Comment by mmolimar** [comment]
Hi @srikant-mvs 
That might be due to how the commit-offset is configured. You can have a look to the [FAQ](http://kafka-connect-fs.readthedocs.io/en/latest/faq.html).

**Comment by srikant-mvs** [comment]
I saw the FAQ Section, but unable to understand where to change or configure.

Please see my configuration, let me know if I am missing something
Script to start the connector
export CLASSPATH="$(find target/ -type f -name '*.jar'| grep '\-package' | tr '\n' ':')"
$CONFLUENT_HOME/bin/connect-distributed $CONFLUENT_HOME/etc/schema-registry/connect-avro-distributed.properties $CONFLUENT_HOME/etc/kafka/kafka-connect-fs.properties

Offset location in the file  $CONFLUENT_HOME/etc/schema-registry/connect-avro-distributed.properties
# Local storage file for offset data
offset.storage.file.filename=/opt/confluent-kafka/confluent-4.1.0/offsets/connect/connect.offsets
(NOTHING is written in this file connect.offsets file)

The offsets are getting stored in the below topic as per the configuration
offset.storage.topic=connect-offsets

The loaded kafka-connect-fs worker configurations. 
{
	"name": "FsSourceConnector",
	"config": {
		"connector.class": "com.github.mmolimar.kafka.connect.fs.FsSourceConnector",
		"tasks.max": "1",
		"fs.uris": "file:/opt/confluent-kafka/confluent-4.1.0/InputsOutput/File-Source/Distributed/1/",
		"topic": "connect-dist-test",
		"policy.class": "com.github.mmolimar.kafka.connect.fs.policy.SleepyPolicy",
		"policy.sleepy.sleep": "30000",
		"policy.recursive": "true",
		"policy.regexp": ".*",
		"file_reader.class": "com.github.mmolimar.kafka.connect.fs.file.reader.TextFileReader",
                "file_reader.text.encoding": "UTF-8"
	}
}
I have defined a timer of every 30sec to look for changes inside the folder 1,
It picks the content for the first time and after 30secs picks again, See the attached image.

![image](https://user-images.githubusercontent.com/18280467/43252892-3675e3f0-90e1-11e8-96bc-3cc17a05fad8.png)

**Comment by mmolimar** [comment]
Please, read [this](http://kafka.apache.org/documentation/#brokerconfigs) and all related things.

**Comment by mmolimar** [comment]
Mmmm... pretty weird, maybe an encoding issue?

**Comment by brianereynolds** [comment]
@srikant-mvs - What offset properties did you provide for the task?
