### ISSUE TITLE
Kerberos Authentication for kafka-connect-fs???

### ISSUE THREAD

**Issue by rajilion** [mmolimar/kafka-connect-fs#37]
name=FsSourceConnector
connector.class=com.github.mmolimar.kafka.connect.fs.FsSourceConnector
tasks.max=1
fs.uris=hdfs://host/user/hive/warehouse/avro_test_db.db/re_avro_formatted/
topic=kafka-connect-fs
policy.class=com.github.mmolimar.kafka.connect.fs.policy.HdfsFileWatcherPolicy
policy.recursive=true
policy.regexp=.*
file_reader.class=com.github.mmolimar.kafka.connect.fs.file.reader.AvroFileReader

I am using the above property to push the data from hdfs to Kafka but i get the below exception

org.apache.hadoop.ipc.RemoteException(org.apache.hadoop.security.AccessControlException): SIMPLE authentication is not enabled.  Available:[TOKEN, KERBEROS]

so is there anyways i could do kerberos authentication?

**Comment by mmolimar** [comment]
Hi.
Yes, you have to configure the ``core-site.xml`` file properly for HDFS.

**Comment by rajilion** [comment]
Hi, 

Yes I was looking for some properties to configure Hadoop conf directory but I could not find any.  Can you please help me with it?

**Comment by rajilion** [comment]
i am running this script on my edge node and i can execute all Hadoop commands over there

**Comment by rajilion** [comment]
and do i need to add core-site.xml and hdfs-site.xml in code to use host  as nameservice1 in hdfs uri?

**Comment by matthew-grant** [comment]
Also curious about this, we only use kerberos auth. Will see if we can get it working. @rajilion  did you ever get it working??

**Comment by matthew-grant** [comment]
would love to pass in locations for core-site.xml, hdfs-site.xml, hive-site.xml, krb5.conf, etc.

**Comment by jrevillard** [comment]
Dear @mmolimar,

So if I understand from this issue, the Hadoop conf must be in the class-path ? It's not possible to specify a configuration for a specific task ?

Best

**Comment by mmolimar** [comment]
You can set some file system configs via config properties in the connectors ``policy.fs.<fs_property>``. See docs [here](https://kafka-connect-fs.readthedocs.io/en/latest/config_options.html#general).

If these configs are not enough, you should configure your Hadoop conf file.

**Comment by jrevillard** [comment]
Ok thx @mmolimar  but I'm still fighting with this configuration.

Would you be able to share a working example for kerberos authentication please ?

Best,
Jerome

**Comment by mmolimar** [comment]
I don't have right now a config like that.
Have you look at [this](https://hadoop.apache.org/docs/current/hadoop-project-dist/hadoop-common/SecureMode.html)?

**Comment by jrevillard** [comment]
Yes, I basically took my core-site.xml and hdfs-site.xml configurations and put them all in policy.fs properties (I took only the relevant once at the beginning but as it was still not working, I took all). The properties are taken into account as the fact that the cluster is in HA is well taken into account.

The issue is authentication. I have exactly the same message as at the beginning of this issue. 

Krb5.conf, keytab is ok as Kafka connection works... So the only problem is that hdfs does not setup Kerberos authentication dispute the fact that this specified in the configuration.

Thanks for your help @mmolimar

P.S: do you prefer that I open a new issue or is it ok to stay here ?

**Comment by jrevillard** [comment]
In fact, I think that I realize that you never call `UserGroupInformation.loginUserFromKeytab` in your source code. THis mean that you expect that kinit is done outside of your connector..... This might be the problem in fact...

**Comment by matt12eagles** [comment]
@jrevillard  we had the same issue..... we never were able to get the connector working on our cluster. instead, we went w/ the hive stream-reactor but that has ALOT to be desired. Would love this connector to be able to support parquet+kerberos....

**Comment by jrevillard** [comment]
@matt12eagles @mmolimar ,

Finally, thanks to the help of @zbaranow it now works !!

Most of the properties can be set using the `policies.fs.xx` attributes.. but not `hadoop.security.authentication`.

So the solution is the following:

1. Create a jar file which will contain a `core-site.xml` file like this :

```
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<configuration>
<property><name>hadoop.security.authentication</name><value>kerberos</value></property>
</configuration>
```

2. put this jar file in the kafka connect class path.
3. set the following 3 properties in your environment:   `KRB5PRINCIPAL` `KRB5KEYTAB` `KRB5CCNAME`
4. also don't forget to setup you krb5.conf file in your OS or for kafka connect using the `java.security.krb5.conf` java property.

Start kafka-connect and create a task like this (properties for HA namenodes etc..):

```
curl -s \
     -X "POST" "https://XXXXXXXXXXXXXX:8083/connectors/" \
     -H "Content-Type: application/json" \
     -d '{
  "name": "source_kafka_connect_fs",
  "config": {
    "connector.class": "com.github.mmolimar.kafka.connect.fs.FsSourceConnector",
    "tasks.max": "1",
    "fs.uris": "hdfs://cluster-research/data",
    "topic": "rcc_qlick-replicate-data",
    "policy.class": "com.github.mmolimar.kafka.connect.fs.policy.HdfsFileWatcherPolicy",
    "policy.recursive": "false",
    "policy.batch_size": "0",
    "policy.cleanup": "none",
    "policy.fs.fs.defaultFS": "hdfs://cluster-research",
    "policy.fs.dfs.nameservices": "cluster-research",
    "policy.fs.dfs.ha.namenodes.cluster-research": "nn1,nn2",
    "policy.fs.dfs.nameservices": "cluster-research",
    "policy.fs.dfs.namenode.rpc-address.cluster-research.nn1": "XXXXXXXXXXXXXX:8020",
    "policy.fs.dfs.namenode.rpc-address.cluster-research.nn2": "XXXXXXXXXXXXXX:8020",
    "policy.fs.dfs.namenode.http-address.cluster-research.nn1": "XXXXXXXXXXXXXX:50070",
    "policy.fs.dfs.namenode.http-address.cluster-research.nn2": "XXXXXXXXXXXXXX:50070",
    "policy.fs.dfs.namenode.https-address.cluster-research.nn1": "XXXXXXXXXXXXXX:50470",
    "policy.fs.dfs.namenode.https-address.cluster-research.nn2": "XXXXXXXXXXXXXX:50470",
    "policy.fs.dfs.client.failover.proxy.provider.cluster-research": "org.apache.hadoop.hdfs.server.namenode.ha.ConfiguredFailoverProxyProvider",
    "policy.fs.dfs.journalnode.edits.dir": "/hadoop/hdfs/journal",
    "file_reader.class": "com.github.mmolimar.kafka.connect.fs.file.reader.SequenceFileReader",
    "file_reader.batch_size": "0"
  }
}
```

Voila !

**Comment by matt12eagles** [comment]
@jrevillard very nice!! Can you please post where in the heart you dropped the files + your policy file?? Would be super helpful. Thanks!

**Comment by mmolimar** [comment]
Great @jrevillard !
That what I was trying to say: it's a built-in functionality that the Hadoop library provides and you have to configure the valid properties as you did!
Congrats ;-)

**Comment by jrevillard** [comment]
> @jrevillard very nice!! Can you please post where in the heart you dropped the files + your policy file?? Would be super helpful. Thanks!

I'm using the cp-kafka-connect docker image so I mounted the volume containing the jar file inside `/etc/kafka-connect/jars`
As far as the policies are concerned, you have all in the curl request (I'm in distributed mode).

@mmolimar this was quite difficult to find and I needed the help of an Hadoop expert (@zbaranow) to find the last problematic part so I think that it would be really good to document it.

Best.
