### ISSUE TITLE
Question: Does the connector tail a local file?

### ISSUE THREAD

**Issue by benitocm** [mmolimar/kafka-connect-fs#45]
Hi,

I am interested in a Kafka File Source connector to ingest in real time the logs generated by an application server (i.e. tail the log file and ingest it into Kafka). Please could you tell me if this connector supports that functionality?

Thanks in advance

**Comment by mmolimar** [comment]
Hi @benitocm 
Currently in this version, the connector doesn't have support to 'tail' files.
