### ISSUE TITLE
Connecting to S3 Without using Access & Secret Key

### ISSUE THREAD

**Issue by sjabiulla** [mmolimar/kafka-connect-fs#50]
Hi,

I am trying to configure S3 Source Connector in AWS EC2 instance and we do NOT want to use access & secret key to connect to s3. We want to grant permission to EC2 instance by providing role to read buckets from S3. How can I achieve using this s3 connector .

**Comment by mmolimar** [comment]
Hi!
The connector uses the hadoop-aws library. If you want to interact with S3, I recommend read [this doc](https://hadoop.apache.org/docs/current/hadoop-aws/tools/hadoop-aws/index.html#Authenticating_via_the_AWS_Environment_Variables).
