### ISSUE TITLE
Specifying header names for files with no header row

### ISSUE THREAD

**Issue by wongelz** [mmolimar/kafka-connect-fs#53]
I can specify header names in `file_reader.delimited.settings.header_names` but it only works when `file_reader.delimited.settings.header = true` (ie. when the file has a header row already). 

For files with no header row (ie. `file_reader.delimited.settings.header = false`), the `file_reader.delimited.settings.header_names` setting is ignored (instead the schema always uses 'column_1, column_2`...).

**Expected behaviour:**
I should be able to specify `file_reader.delimited.settings.header = false` and `file_reader.delimited.settings.header_names=Foo,Bar,...`, and the schema should use the header names Foo,Bar instead of column_1,column_2

**Comment by kylecbrodie** [comment]
@wongelz @mmolimar is this resolved by PR #72? Can this issue be closed?

**Comment by wongelz** [comment]
Thanks @kylecbrodie ! 🥇
