### ISSUE TITLE
Offset management + seek performance

### ISSUE THREAD

**Issue by grantatspothero** [mmolimar/kafka-connect-fs#55]
I noticed that the file reader implementations seem to implement the `seekFile` operation by iterating over each line in the file and throwing it away. This is expensive since every time a file is scanned by the policy, the entire file's contents will be pulled over the network. 

https://github.com/mmolimar/kafka-connect-fs/blob/master/src/main/java/com/github/mmolimar/kafka/connect/fs/file/reader/TextFileReader.java#L113-L125

Instead, if we implement `seekFile` using the `fsdatainputstream.seek` method, then we can only pull out the data that has been appended since the last commit of offsets. For the common case of immutable files, this will be nothing, and thus we will get a significant performance boost. 

https://hadoop.apache.org/docs/current/hadoop-project-dist/hadoop-common/filesystem/fsdatainputstream.html#Seekable.seek.28s.29

(the hadoop s3 filesystem implementation of seek uses RANGE headers to selectively pull only the requested bytes) 
https://hadoop.apache.org/docs/r2.5.2/api/org/apache/hadoop/fs/s3/package-summary.html

The catch:
the `seek` interface takes a `byte` in the file not a line number, so to do this instead of storing a line number as our offset in kafka connect we would have to store a `byte` offset. This would obviously break backwards compatibility of the connector, but it would come at a significant performance improvement.

Is there a reason offsets are stored as line numbers and not bytes/is there a problem you ran into along the way? Would you be open to this change if I were to contribute it?

Thanks for all your work on the connector, it has been super helpful so far.

**Comment by mmolimar** [comment]
Hi!
That's what happens with the Avro file reader actually. Which is your use case?
It'd be great to have this improvement (but taking care with the "plain text" readers -text and Univocity readers). So, contributions are very welcome!
I'd include in the offset stored both, the record/line number and the actual offset itself.

Many thanks!

**Comment by grantatspothero** [comment]
Our use case is ingesting a bunch of new line delimited JSON files from s3. Since we have a lot of data, pulling down all the data over the network every time a scrape happens causes the scrape to be very slow. 

About storing the offset and line number, storing the line number and the byte offset is possible for backwards compat purposes. If the byte offset doesn't exist in offset storage then the current behavior can stay the same and if it does exist then we can have the improved seek behavior.

I will try my best to contribute something within the next few weeks, thanks for being open to PRs!

**Comment by mmolimar** [comment]
Great!
Looking forward ;-)
