### ISSUE TITLE
What if executions AtomicInterger variable reach to its max limit. 

### ISSUE THREAD

**Issue by deepakrghv** [mmolimar/kafka-connect-fs#56]
Hi 

If AtomicInteger variable reach to its max limit, after that it will set back to negative value. 

    @Override
    public final Iterator<FileMetadata> execute() throws IOException {
        if (hasEnded()) {
            throw new IllegalWorkerStateException("Policy has ended. Cannot be retried.");
        }
        preCheck();

        executions.incrementAndGet();
        Iterator<FileMetadata> files = Collections.emptyIterator();
        for (FileSystem fs : fileSystems) {
            files = concat(files, listFiles(fs));
        }

        postCheck();

        return files;
    }

**Comment by mmolimar** [comment]
Hi!
Actually it's an AtomicLong but yes, it could be possible an overflow eventually. I'll add a check for that.
Thanks!

**Comment by deepakrghv** [comment]
Hi 

Thanks for your quick reply. 
Actually in previous version it was AtomicInteger and this variable can be set like below 

if (getExecutions() > 1) {
			executions.decrementAndGet();
		}

BR
