### ISSUE TITLE
Question: Does this handle processing files in real-time or near real-time?

### ISSUE THREAD

**Issue by dmarupov** [mmolimar/kafka-connect-fs#61]
I would like to know if this connector handles processing files while they are being written to?
For example: if I have a file.txt and I am continuously writing to it and want the records to be processed as soon as they are written line by line?
I would appreciate the answer to this question, thank you in advance.

**Comment by mmolimar** [comment]
Hi.
Yes, it'll handle those files based on the policy defined. Also, previous records processed will be ignored by the connector.
