### ISSUE TITLE
Question: Is there a way to specify the record key ?

### ISSUE THREAD

**Issue by mdespriee** [mmolimar/kafka-connect-fs#65]
I'd like to read json-per-line files, and extract a value in each json as record key.
From what I saw in docs and code, it's not possible, but I may have overlooked something

**Comment by mmolimar** [comment]
Hello.
You can read a JSON per file using the connector. Then, if you need to extract values and/or transform the data, you can use SMTs.

**Comment by mdespriee** [comment]
ah, yes of course ! will try asap
