### ISSUE TITLE
Masking on the fly

### ISSUE THREAD

**Issue by bajaj1989** [mmolimar/kafka-connect-fs#7]
Hi,
I have a requirement where I need to stream files in HDFS and put it in kafka topics. On the fly also I need to mast certain fields in each record in the file.
If I have to do so in which file and which method shall I have to do the change needed

**Comment by mmolimar** [comment]
Hi!
If you want to mask the content of some fields in the Kafka message I do recommend not to modify the code of the connector but develop a custom Kafka Stream process to do that instead.

**Comment by bajaj1989** [comment]
I am most interested in the DelimitedFileTextReader.java  Would be great if you could specify the properties specific to that class?
Also when I dig down in this class I didn't find where you set the token(delimiter)?

**Comment by mmolimar** [comment]
Please, read the [docs](http://kafka-connect-fs.readthedocs.io/en/latest/config_options.html#file-readers).

The property is named as FILE_READER_DELIMITED_TOKEN which is in DelimitedFileTextReader class.
