### ISSUE TITLE
Error while running command to get file permissions

### ISSUE THREAD

**Issue by andy-agap** [mmolimar/kafka-connect-fs#73]
Hi, 

```
java.lang.RuntimeException: Error while running command to get file permissions : 
ExitCodeException exitCode=2: ls: cannot access /path/to/file: No such file or directory
```

Encountering this issue where it seems that if a file is created in the directory and later removed, the above error is thrown from filesToProcess(). The connector then goes into a failed state and does not resume.
Am using sleepy policy with text file reader. Is there any configuration to set for minimum age of file or for retrying upon this particular error thrown?

Thanks.

**Comment by mmolimar** [comment]
Hi @andy-agap 
Which version are you using?
