### ISSUE TITLE
How to skip Kerberos Authentication for kafka-connect-fs for SFTP

### ISSUE THREAD

**Issue by CodeDevBook** [mmolimar/kafka-connect-fs#76]
Hi,
I am trying to fetch the file from SFTP using this connector but it keep asking me Kerberos credentials everytime when we start the connector on the console
Kerberos username [user name]:
Kerberos password

**All I want is to skip the kerberos credentials and only use private key which is I am already providing.**
Below is the property file for SFTP

name=FsSourceConnector
connector.class=com.github.mmolimar.kafka.connect.fs.FsSourceConnector
tasks.max=1
policy.class=com.github.mmolimar.kafka.connect.fs.policy.SimplePolicy
policy.sleepy.sleep=5000
policy.recursive=true
policy.regexp=^.*\.txt$
policy.batch_size=0
file_reader.class=com.github.mmolimar.kafka.connect.fs.file.reader.TextFileReader
file_reader.batch_size=0
**fs.uris=sftp://<user_name>:@host-name:22/directory/?preferredAuthentications=publickey,password**
fs.sftp.keyfile=C:/Users/directory/key.ppk
topic=sftp-topic
policy.fs.fs.sftp.impl=org.apache.hadoop.fs.sftp.SFTPFileSystem

@mmolimar ,
Kindly suggest me the resolution for this
**Is the "fs.uris" correct here ? If not then what is the correct property to skip this authentication.**

**Comment by mmolimar** [comment]
Hi @CodeDevBook!

You should change the ``PreferredAuthentications`` in Jsch.
Setting ``JSch.setConfig("PreferredAuthentications", "publickey,keyboard-interactive,password");`` [here](https://github.com/mmolimar/kafka-connect-fs/blob/master/src/main/java/com/github/mmolimar/kafka/connect/fs/policy/AbstractPolicy.java#L82) should work.

**Comment by CodeDevBook** [comment]
> Hi @CodeDevBook!
> 
> You should change the `PreferredAuthentications` in Jsch.
> Setting `JSch.setConfig("PreferredAuthentications", "publickey,keyboard-interactive,password");` [here](https://github.com/mmolimar/kafka-connect-fs/blob/master/src/main/java/com/github/mmolimar/kafka/connect/fs/policy/AbstractPolicy.java#L82) should work.
