### ISSUE TITLE
Memory is not freed after all files have been processed and moved from s3 bucket

### ISSUE THREAD

**Issue by shaiyahleba** [mmolimar/kafka-connect-fs#77]
Hi,

When using the connector to read files from s3 into kafka we see that the memory increases during processing time (for example reaches 25gb) and after all files have been processed and moved to a different directory the memory doesn't decrease (remains at 25gb). If at this point we stream some additional new files to the same s3 bucket, the connector processes them and the memory increases with respect to the new data (for example increases from 25gb to 30gb), but again after all new files have been processed the memory still not being freed (remains on 30gb) and so on.

We use the Sleepy policy and we tried all different kinds of batching approaches using the file_reader.batch_size and policy.batch_size properties.

In addition, the policy.cleanup 'move' to a different s3 bucket didn't work, we had to move the files manually.

We're using version 1.1.0

Example config that we're using:

{
  "name": "source-connector-9",
  "config": {
    "connector.class": "com.github.mmolimar.kafka.connect.fs.FsSourceConnector",
    "tasks.max": "20",
    "errors.tolerance": "all",
    "errors.log.enable": "true",
    "errors.log.include.messages": "true",
    "fs.uris": "s3a://test-archive/2020-07-20_10-27-40-6gb",
    "topic": "test-9",
    "policy.regexp": ".*",
    "file_reader.batch_size": "300000",
    "policy.class": "com.github.mmolimar.kafka.connect.fs.policy.SleepyPolicy",
    "policy.sleepy.sleep": "15000",
    "policy.fs.fs.s3a.secret.key": "****",
    "file_reader.class": "com.github.mmolimar.kafka.connect.fs.file.reader.TextFileReader",
    "policy.fs.fs.s3a.access.key": "****",
    "policy.recursive": "true",
    "policy.batch_size": "1",
    "file_reader.text.compression.type": "gzip",
    "policy.cleanup": "move",
    "policy.cleanup.move": "s3a://test-archive/processed"
  }
}

Thanks in advance.

**Comment by mmolimar** [comment]
Hi @shaiyahleba!

If using the ``file_reader.batch_size`` property, records will be returned to the worker task and then they should be freed by the GC at some point. Which is the memory config of your JVM and version of your JDK?

By the way, which are the sizes of those files?

**Comment by shaiyahleba** [comment]
Hi,

Thanks for replying.

jvm.args = -Xms512m, -Xmx40g, -XX:+UseG1GC, -XX:MaxGCPauseMillis=20, -XX:InitiatingHeapOccupancyPercent=35, -XX:+ExplicitGCInvokesConcurrent, -XX:MaxInlineLevel=15, -Djava.awt.headless=true, -Dcom
.sun.management.jmxremote=true, -Dcom.sun.management.jmxremote.authenticate=false, -Dcom.sun.management.jmxremote.ssl=false, -Dkafka.logs.dir=/var/log/kafka, -Dlog4j.configuration=file:/etc/kafka/connect-
log4j.properties
jvm.spec = Azul Systems, Inc., OpenJDK 64-Bit Server VM, 1.8.0_212, 25.212-b04

The files in s3 are gzipped. The size of each file ~7mb compressed, ~100mb uncompressed.
We have ~6gb of compressed files.

Thanks

**Comment by mmolimar** [comment]
Have you tried setting the max memory to something like 16g or so (even less)? On the other hand, which is the behaviour using the Oracle JDK?
