### ISSUE TITLE
Getting FileNotFoundException when creating reader for that particular source-file path (Tag:-v0.2)

### ISSUE THREAD

**Issue by deepakrghv** [mmolimar/kafka-connect-fs#79]
Hi 

We had observed that **filesToProcess()** method call returns the file list but while creating reader inside **policy.offer()** method, it is getting exception with message i.e. "An exception occurred while creating reader for file" 

Just to add, We are reading files from S3 bucket and using sleepy policy. 
Here the piece of code,

```
 List<FileMetadata> files = filesToProcess();
            files.forEach(metadata -> {
                try {
                    log.info("Processing records for file {}", metadata);
                    FileReader reader = policy.offer(metadata, context.offsetStorageReader());
```

and we have added a check to verify if that particular file path is existed or not 

```
        FileSystem current = fileSystems.stream()
                .filter(fs -> metadata.getPath().startsWith(fs.getWorkingDirectory().toString()))
                .findFirst().orElse(null);
        
        //Added by me, to check if path is present or not.
        **if (!current.exists(new Path(metadata.getPath())))** {
            log.info("File {} not exists in S3 while creating reader", metadata);
            return null;
        }
```

We had observed, that path is not present, this was reason the exception was coming.
Just want to know why the file path listed earlier in **filesToProcess**() call, but it is not exist when the same path is checked specifically as per above highlighted line in code snippet. 

BR
Deepak Raghav

**Comment by mmolimar** [comment]
Have you tried with a newer version? V0.2 is pretty old.

**Comment by deepakrghv** [comment]
Hi 

We can not upgrade it currently, It would be helpful if you share why that behavior is happening on this version(0.2).

**Comment by mmolimar** [comment]
Not sure why that's happening.
I'd recommend applying an upgrade to the S3 deps and maybe apply a double check to avoid that error.

**Comment by deepakrghv** [comment]
We put null check before creating reader. closing this discussion here
Thanks
